LIST P=PIC16F1827
#include<p16f1827.inc>

CNT0	EQU	0x70
CNT1	EQU	0x71
CNT2	EQU	0x72
CNT3 EQU 0x73
CNT4 EQU 0x74
CNT4_DEFAULT EQU d'40'
CNT4_HALF EQU d'20'
TMP EQU 0x74
__CONFIG	_CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_OFF
__CONFIG	_CONFIG2, _WRT_OFF & _PLLEN_OFF & _STVREN_OFF & _BORV_LO & _LVP_OFF

ORG 0x0000
    CLRF PORTA
    CLRF PORTB
    BSF BSR, BSR0
    ; バンク1
    ; クロックを4MHzに設定
    MOVLW B'01101000'
    MOVWF OSCCON
    BSF BSR, BSR1
    ; バンク3
    ; ディジタル入力を受け入れるようにする
    ; CLRF ANSELAをすると何故かRA4の動きがXORみたいな動きをするようになる。
    ; 今回はANSELAを行わないことで対応
    CLRF ANSELB
    ; バンク1
    BSF BSR, BSR0
    BCF BSR, BSR1
    MOVLW 0x00
    MOVWF TRISA
    MOVLW 0x30
    MOVWF TRISB
    ; バンク0
    BCF BSR, BSR0
    CLRF PORTA
    CLRF PORTB
LOOP
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE0
    DECFSZ CNT3
    GOTO _STATE0
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    ; STATE0終了
STATE1
    DECFSZ CNT3
    GOTO _STATE1
    ; STATE1終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE2
    DECFSZ CNT3
    GOTO _STATE2
    ; STATE2終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE3
    DECFSZ CNT3
    GOTO _STATE3
    ; STATE3終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE4
    DECFSZ CNT3
    GOTO _STATE4
    ; STATE4終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE5
    DECFSZ CNT3
    GOTO _STATE5    
    ; STATE5終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE6
    DECFSZ CNT3
    GOTO _STATE6
    ; STATE6終了
    MOVLW D'240'
    MOVWF CNT3
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
STATE7
    DECFSZ CNT3
    GOTO _STATE7
    ; STATE7終了
    GOTO LOOP

_STATE0
    CALL LED1
    CALL LED2
    CALL LED3
    CALL LED4
    CALL LED5
    CALL LED6
    GOTO STATE0
    
_STATE1
    MOVF CNT4, W
    SUBLW CNT4_HALF
    BTFSS STATUS, C
    GOTO _STATE1_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED4
    CALL LED5
    CALL LED6
    MOVF CNT4, W
    BTFSS STATUS, Z
    GOTO _STATE1_DEC
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    GOTO STATE1
_STATE1_ON
    CALL LED1
    CALL LED2
    CALL LED3
    CALL LED4
    CALL LED5
    CALL LED6
    DECF CNT4
    GOTO STATE1
_STATE1_DEC
    DECF CNT4
    GOTO STATE1

_STATE2
    CALL LED4
    CALL LED5
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    GOTO STATE2
    
_STATE3
    MOVF CNT4, W
    SUBLW CNT4_HALF
    BTFSS STATUS, C
    GOTO _STATE3_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    MOVF CNT4, W
    BTFSS STATUS, Z
    GOTO _STATE3_DEC
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    GOTO STATE3
_STATE3_ON
    CALL LED4
    CALL LED5
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    DECF CNT4
    GOTO STATE3
_STATE3_DEC
    DECF CNT4
    GOTO STATE3

_STATE4
    CALL LED6
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    GOTO STATE4

_STATE5
    MOVF CNT4, W
    SUBLW CNT4_HALF
    BTFSS STATUS, C
    GOTO _STATE5_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    MOVF CNT4, W
    BTFSS STATUS, Z
    GOTO _STATE5_DEC
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    GOTO STATE5
_STATE5_ON
    CALL LED6
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    DECF CNT4
    GOTO STATE5
_STATE5_DEC
    DECF CNT4
    GOTO STATE5

_STATE6
    CALL LED7
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    GOTO STATE6

_STATE7
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    GOTO STATE7

LED_CLEAR
    MOVF PORTA, W
    ANDLW 0b11100011
    ADDLW 0x00
    MOVWF PORTA
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x00
    MOVWF PORTB
    CALL TIMER_LED
    RETURN

LED1
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x07
    MOVWF PORTB
    MOVLW 0x04
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED2
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0b
    MOVWF PORTB
    MOVLW 0x04
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED3
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0d
    MOVWF PORTB
    MOVLW 0x04
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED4
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x07
    MOVWF PORTB
    MOVLW 0x08
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED5
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0b
    MOVWF PORTB
    MOVLW 0x08
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED6
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x07
    MOVWF PORTB
    MOVLW 0x10
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED7
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0e
    MOVWF PORTB
    MOVLW 0x04
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED8
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0d
    MOVWF PORTB
    MOVLW 0x08
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED9
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0e
    MOVWF PORTB
    MOVLW 0x08
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED10
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0b
    MOVWF PORTB
    MOVLW 0x10
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED11
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0d
    MOVWF PORTB
    MOVLW 0x10
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED12
    MOVLW 0b11100011
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW 0x11110000
    ADDLW 0x0e
    MOVWF PORTB
    MOVLW 0x10
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN

;1ms
TIMER_LED
	MOVLW	D'199'
	MOVWF	CNT1
TIMER_LED_LABEL1
	NOP
	NOP
	DECFSZ	CNT1,F
	GOTO	TIMER_LED_LABEL1
	RETURN

TIMER_10MS
	MOVLW	D'19'
	MOVWF	CNT1
TIMER_10MS_LABEL1
	MOVLW	D'174'
	MOVWF	CNT2
TIMER_10MS_LABEL2
	DECFSZ	CNT2,F
	GOTO	TIMER_10MS_LABEL2
	DECFSZ	CNT1,F
	GOTO	TIMER_10MS_LABEL1
	NOP
	RETURN

TIMER_1000MS
	MOVLW	D'173'
	MOVWF	CNT1
TIMER_1000MS_LABEL1
	MOVLW	D'191'
	MOVWF	CNT2
TIMER_1000MS_LABEL2
	DECFSZ	CNT2,F
	GOTO	TIMER_1000MS_LABEL2
	NOP
	DECFSZ	CNT1,F
	GOTO	TIMER_1000MS_LABEL1
	NOP
	RETURN

end