LIST P=PIC16F1827
#include<p16f1827.inc>

CNT0	EQU	0x70
CNT1	EQU	0x71
CNT2	EQU	0x72
CNT3 EQU 0x73
; TODO: CNT3_DEFAULTを廃止してメモリからデータを読むようにする
;20.825
CNT3_1MIN EQU D'22'
;62.5
CNT3_3MIN EQU D'64'
;104.1666...
CNT3_5MIN EQU D'105'
CNT4 EQU 0x74
CNT4_DEFAULT EQU D'80'
CNT5 EQU 0x75
CNT5_DEFAULT EQU D'40'
CNT5_HALF EQU D'20'

CNT3_MEM EQU 0x76

BUZZER EQU D'1'
 
 START_SW EQU D'4'
 RESET_SW EQU D'5'

__CONFIG	_CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOREN_OFF & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_OFF
__CONFIG	_CONFIG2, _WRT_OFF & _PLLEN_OFF & _STVREN_OFF & _BORV_LO & _LVP_OFF

ORG 0x0000
    CLRF PORTA
    CLRF PORTB
    BSF BSR, BSR0
    ; バンク1
    ; クロックを4MHzに設定
    MOVLW B'01101000'
    MOVWF OSCCON
    BSF BSR, BSR1
    ; バンク3
    ; ディジタル入力を受け入れるようにする
    CLRF ANSELB
    ; バンク1
    BSF BSR, BSR0
    BCF BSR, BSR1
    MOVLW 0x00
    MOVWF TRISA
    MOVLW 0x30
    MOVWF TRISB
    ; バンク0
    BCF BSR, BSR0
    CLRF PORTA
    CLRF PORTB
LOOP
    ; 離し終わるまで待機
    ; どこかからボタンを押されてスキップしてきた場合はブザーを鳴らす
    BTFSC PORTB, RESET_SW
    CALL SELECT_BUZZER
LOOP_LABEL1
    CALL _SELECT1
    BTFSC PORTB, RESET_SW
    GOTO LOOP_LABEL1
SELECT1
    CALL _SELECT1
    BTFSS PORTB, START_SW
    GOTO SELECT1_LABEL1
    MOVLW CNT3_1MIN
    MOVWF CNT3_MEM
    GOTO STATE0
SELECT1_LABEL1
    BTFSS PORTB, RESET_SW
    GOTO SELECT1
    ; 離し終わるまで待機
    CALL LED_CLEAR
    CALL SELECT_BUZZER
SELECT1_LABEL2
    CALL _SELECT3
    BTFSC PORTB, RESET_SW
    GOTO SELECT1_LABEL2

SELECT3
    CALL _SELECT3
    BTFSS PORTB, START_SW
    GOTO SELECT3_LABEL1
    MOVLW CNT3_3MIN
    MOVWF CNT3_MEM
    GOTO STATE0
SELECT3_LABEL1
    BTFSS PORTB, RESET_SW
    GOTO SELECT3
    ; 離し終わるまで待機
    CALL LED_CLEAR
    CALL SELECT_BUZZER
SELECT3_LABEL2
    CALL _SELECT5
    BTFSC PORTB, RESET_SW
    GOTO SELECT3_LABEL2

SELECT5
    CALL _SELECT5
    BTFSS PORTB, START_SW
    GOTO SELECT5_LABEL1
    MOVLW CNT3_5MIN
    MOVWF CNT3_MEM
    GOTO STATE0
SELECT5_LABEL1
    BTFSS PORTB, RESET_SW
    GOTO SELECT5
    ; 離し終わるまで待機
    CALL LED_CLEAR
    CALL SELECT_BUZZER
SELECT5_LABEL2
    CALL _SELECT1
    BTFSC PORTB, RESET_SW
    GOTO SELECT5_LABEL2
    GOTO LOOP

SELECT_BUZZER
    MOVLW D'51'
    MOVWF CNT5
SELECT_BUZZER_LABEL1
    DECFSZ CNT5
    GOTO SELECT_BUZZER_LABEL2
    RETURN
SELECT_BUZZER_LABEL2
    BSF PORTA, BUZZER
    ; 1ms
    CALL TIMER_LED
    BCF PORTA, BUZZER
    ; 1ms
    CALL TIMER_LED
    GOTO SELECT_BUZZER_LABEL1
    
_SELECT1
    CALL LED2
    CALL LED6
    CALL LED7
    CALL LED11
    RETURN

_SELECT3
    CALL LED1
    CALL LED2
    CALL LED3
    CALL LED5
    CALL LED6
    CALL LED7
    CALL LED9
    CALL LED12
    CALL LED11
    CALL LED10
    RETURN

_SELECT5
    CALL LED3
    CALL LED2
    CALL LED1
    CALL LED4
    CALL LED6
    CALL LED7
    CALL LED9
    CALL LED12
    CALL LED11
    CALL LED10
    RETURN

STATE0
    GOTO _STATE0
STATE1
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE1_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE1_LABEL2
    GOTO STATE2
STATE1_LABEL2
    DECFSZ CNT4
    GOTO _STATE1
    GOTO STATE1_LABEL1
    
STATE2
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE2_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE2_LABEL2
    GOTO STATE3
STATE2_LABEL2
    DECFSZ CNT4
    GOTO _STATE2
    GOTO STATE2_LABEL1

STATE3
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE3_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE3_LABEL2
    GOTO STATE4
STATE3_LABEL2
    DECFSZ CNT4
    GOTO _STATE3
    GOTO STATE3_LABEL1

STATE4
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE4_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE4_LABEL2
    GOTO STATE5
STATE4_LABEL2
    DECFSZ CNT4
    GOTO _STATE4
    GOTO STATE4_LABEL1

STATE5
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE5_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE5_LABEL2
    GOTO STATE6
STATE5_LABEL2
    DECFSZ CNT4
    GOTO _STATE5
    GOTO STATE5_LABEL1

STATE6
    MOVF CNT3_MEM, W
    MOVWF CNT3
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
STATE6_LABEL1
    MOVLW CNT4_DEFAULT
    MOVWF CNT4
    DECFSZ CNT3
    GOTO STATE6_LABEL2
    GOTO STATE7
STATE6_LABEL2
    DECFSZ CNT4
    GOTO _STATE6
    GOTO STATE6_LABEL1
    
STATE7
    ; STATE7は砂が全部落ちたアニメーション
    GOTO _STATE7

STATE8
    ; STATE8は消灯のみ
    DECFSZ CNT3
    GOTO _STATE8
    ; STATE8終了
    GOTO LOOP

; LED1~6を光らせながら、ブザーを1秒間鳴らす
; 以下のような書き方をするとブザーが動かなかったため、各PORTの書き込みは1度で済むようなコードにした。
; 動かなかった原因は書き込んだ直後にメモリを読み込むと動作が安定しないと結論づけた(多分違う)
; BSF PORTA, 1
; CALL LED1
; BCF PORTA, 1
; CALL LED2
_STATE0
    MOVLW D'167'
    MOVWF CNT5
_STATE0_LABEL1
    DECFSZ CNT5
    GOTO _STATE0_LABEL2
    GOTO STATE1
_STATE0_LABEL2
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    ; LED1 BUZZER ON
    MOVLW B'00000110'
    MOVWF PORTA
    MOVLW B'00000111'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED2 BUZZER OFF
    MOVLW B'00000100'
    MOVWF PORTA
    MOVLW B'00001011'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED3 BUZZER ON
    MOVLW B'00000110'
    MOVWF PORTA
    MOVLW B'00001101'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED4 BUZZER OFF
    MOVLW B'00001000'
    MOVWF PORTA
    MOVLW B'00000111'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED5 BUZZER ON
    MOVLW B'00001010'
    MOVWF PORTA
    MOVLW B'00001011'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED6 BUZZER OFF
    MOVLW B'00010000'
    MOVWF PORTA
    MOVLW B'00000111'
    MOVWF PORTB
    CALL TIMER_LED
    GOTO _STATE0_LABEL1

_STATE1
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    CALL LED1
    CALL LED2
    CALL LED3
    CALL LED4
    CALL LED5
    CALL LED6
    GOTO STATE1_LABEL2
    
_STATE2
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    MOVF CNT5, W
    SUBLW CNT5_HALF
    BTFSS STATUS, C
    GOTO _STATE2_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED4
    CALL LED5
    CALL LED6
    MOVF CNT5, W
    BTFSS STATUS, Z
    GOTO _STATE2_DEC
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
    GOTO STATE2_LABEL2
_STATE2_ON
    CALL LED1
    CALL LED2
    CALL LED3
    CALL LED4
    CALL LED5
    CALL LED6
    DECF CNT5
    GOTO STATE2_LABEL2
_STATE2_DEC
    DECF CNT5
    GOTO STATE2_LABEL2

_STATE3
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    CALL LED4
    CALL LED5
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    GOTO STATE3_LABEL2
    
_STATE4
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    MOVF CNT5, W
    SUBLW CNT5_HALF
    BTFSS STATUS, C
    GOTO _STATE4_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    MOVF CNT5, W
    BTFSS STATUS, Z
    GOTO _STATE4_DEC
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
    GOTO STATE4_LABEL2
_STATE4_ON
    CALL LED4
    CALL LED5
    CALL LED6
    CALL LED10
    CALL LED11
    CALL LED12
    DECF CNT5
    GOTO STATE4_LABEL2
_STATE4_DEC
    DECF CNT5
    GOTO STATE4_LABEL2

_STATE5
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    CALL LED6
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    GOTO STATE5_LABEL2

_STATE6
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    MOVF CNT5, W
    SUBLW CNT5_HALF
    BTFSS STATUS, C
    GOTO _STATE6_ON
    ; 点滅
    CALL LED_CLEAR
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    MOVF CNT5, W
    BTFSS STATUS, Z
    GOTO _STATE6_DEC
    MOVLW CNT5_DEFAULT
    MOVWF CNT5
    GOTO STATE6_LABEL2
_STATE6_ON
    CALL LED6
    CALL LED8
    CALL LED9
    CALL LED10
    CALL LED11
    CALL LED12
    DECF CNT5
    GOTO STATE6_LABEL2
_STATE6_DEC
    DECF CNT5
    GOTO STATE6_LABEL2

; LED7~12を光らせながら、ブザーを1秒間鳴らす
; 以下のような書き方をするとブザーが動かなかったため、各PORTの書き込みは1度で済むようなコードにした。
; 動かなかった原因は書き込んだ直後にメモリを読み込むと動作が安定しないと結論づけた(多分違う)
; BSF PORTA, 1
; CALL LED1
; BCF PORTA, 1
; CALL LED2
_STATE7
    MOVLW D'167'
    MOVWF CNT5
_STATE7_LABEL1
    DECFSZ CNT5
    GOTO _STATE7_LABEL2
    GOTO STATE8
_STATE7_LABEL2
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    ; LED7 BUZZER ON
    MOVLW B'00000110'
    MOVWF PORTA
    MOVLW B'00001110'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED8 BUZZER OFF
    MOVLW B'00001000'
    MOVWF PORTA
    MOVLW B'00001101'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED9 BUZZER ON
    MOVLW B'00001010'
    MOVWF PORTA
    MOVLW B'00001110'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED10 BUZZER OFF
    MOVLW B'00010000'
    MOVWF PORTA
    MOVLW B'00001011'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED11 BUZZER ON
    MOVLW B'00010010'
    MOVWF PORTA
    MOVLW B'00001101'
    MOVWF PORTB
    CALL TIMER_LED
    ; LED12 BUZZER OFF
    MOVLW B'00010000'
    MOVWF PORTA
    MOVLW B'00001110'
    MOVWF PORTB
    CALL TIMER_LED
    GOTO _STATE7_LABEL1
    
_STATE8
    BTFSC PORTB, RESET_SW
    GOTO LOOP
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    CALL LED_CLEAR
    GOTO STATE8

LED_CLEAR
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW 0x00
    MOVWF PORTB
    MOVLW 0x00
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN

LED1
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00000111'
    MOVWF PORTB
    MOVLW B'00000100'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED2
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001011'
    MOVWF PORTB
    MOVLW B'00000100'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED3
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001101'
    MOVWF PORTB
    MOVLW B'00000100'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED4
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00000111'
    MOVWF PORTB
    MOVLW B'00001000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED5
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001011'
    MOVWF PORTB
    MOVLW B'00001000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED6
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00000111'
    MOVWF PORTB
    MOVLW B'00010000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED7
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001110'
    MOVWF PORTB
    MOVLW B'00000100'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED8
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001101'
    MOVWF PORTB
    MOVLW B'00001000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED9
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001110'
    MOVWF PORTB
    MOVLW B'00001000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED10
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001011'
    MOVWF PORTB
    MOVLW B'00010000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED11
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001101'
    MOVWF PORTB
    MOVLW B'00010000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN
LED12
    MOVLW B'11100011'
    ANDWF PORTA, F
    MOVF PORTB, W
    ANDLW B'11110000'
    ADDLW B'00001110'
    MOVWF PORTB
    MOVLW B'00010000'
    ADDWF PORTA, F
    CALL TIMER_LED
    RETURN

;1ms
TIMER_LED
	MOVLW	D'199'
	MOVWF	CNT1
TIMER_LED_LABEL1
	NOP
	NOP
	DECFSZ	CNT1,F
	GOTO	TIMER_LED_LABEL1
	RETURN

TIMER_1000MS
	MOVLW	D'173'
	MOVWF	CNT1
TIMER_1000MS_LABEL1
	MOVLW	D'191'
	MOVWF	CNT2
TIMER_1000MS_LABEL2
	DECFSZ	CNT2,F
	GOTO	TIMER_1000MS_LABEL2
	NOP
	DECFSZ	CNT1,F
	GOTO	TIMER_1000MS_LABEL1
	NOP
	RETURN

end